---
title: Mike Ledger
author: Mike Ledger
date: 8 January, 2018
description: My resume
---
#+BEGIN_HTML
<div id="header">
<div id="details">
#+END_HTML

|----------+-------------------|
|          | *Mike Ledger*     |
| Email    | [[mailto:mike@quasimal.com][mike@quasimal.com]] |
| Website  | [[http://quasimal.com][quasimal.com]]      |
| Phone    | +61 403 154 462   |
| Accounts | [[https://github.com/mikeplus64][GitHub]], [[http://hackage.haskell.org/user/MikeLedger][Hackage]]   |
|----------+-------------------|

#+BEGIN_HTML
<img id="gravatar" alt="Gravatar" src="https://secure.gravatar.com/avatar/c9f4d28a5240e2b99d83a5848f49c01f?s=200" title="Gravatar (Wallace and Gromit: A Grand Day Out)" />
<div style="clear: both"></div>
</div>
</div>

<div id="content">
#+END_HTML

I'm a programmer (and [[http:/gallery][occasional artist]]) living in Canberra, Australia. I'm
currently working part-time at Ricardo Rail while studying at the ANU here in
Canberra.

#+BEGIN_HTML 
<div id="skills">
#+END_HTML

|------------+--------+---------------+--------------|
| Haskell    | Rust   | TypeScript    | Python       |
| Nix        | Design | Java          | HTML/CSS     |
| JavaScript | Git    | Data scraping | SQL          |
| NLP        | React  | RDF           | ... and more |
|------------+--------+---------------+--------------|


#+BEGIN_HTML
</div>
#+END_HTML

** Experience

[[https://respecify.com][Respecify]], a requirements authoring tool utilising constrained natural language.
I have developed this (so far) as a one-man team. Respecify was presented in
Lisbon for [[http://re2017.org][RE'17]]. [[http://ieeexplore.ieee.org/document/8049164/][Paper available online at IEEE Xplore]].

Respecify involves a novel parser generator for creating English grammars, which
features a simple functional language which individual parsers within a grammar
produce (as stack-based virtual machine code) as results. The accompanying
interpreter then "runs" the parse results which enables simple grammars to be
able to reliably extract information (such as component hierarchies) from
natural language text.

[[https://kuachicups.com][Kuachi Cups]], a community tournament website. Features fair double
elimination brackets, single elimination brackets, and group / round robin
brackets. Uses Discord as the basis for logins as that is what the community
itself is based around. Also features a dynamic overlay creator for streamers to
use when streaming tournament games, featuring a WebRTC based remote-control for
the streamer to control their overlay through e.g. a OBS Studio panel.

[[https://rpd.transport.engineering][RPD Stabling Database]], an online database UI for aiding management of train
stabling in the Sydney trains network. Allows for a user to query the current
allocation of train stabling across the network using an interactive map in
addition to with a powerful query engine. This is a Haskell/Servant server using
PostgreSQL to serve a TypeScript/React frontend.

[[https://github.com/mikeplus64/solid-typefu-router5][solid-typefu-router5]] a TypeScript/SolidJS library for type-safe routing, similar
to ~react-router~ but for use with SolidJS. Uniquely it has type-safe ~Link~ and
~Router~ components whose types are determined by what the library user has
specified as their routes; uses a lot of new TypeScript magic to enable e.g.
parsing route definitions at the type-level.

[[https://transportengineering.gitlab.io/com-au][Transport Engineering website]], a simple-ish Hakyll-generated website that runs
in parallel with an older Wordpress-based website.

[[https://github.com/mikeplus64/teamsplat][teamsplat]], a simple team splitter to generate fair teams for 8-ish player games.
Live version available on [[https://teamsplat.herokuapp.com][Heroku]] (because it's free and Good Enough!).

[[https://gitlab.com/transportengineering/rnd/radixtree][radixtree]], a prefix-tree parsing library for Haskell. Used extensively by
Respecify.

[[https://github.com/TransportEngineering/nice-html][nice-html]], a XML/HTML templating library for Haskell. Has distinct template
compilation and rendering phases, which is its main advantage over e.g., Lucid
or Blaze.

[[https://github.com/mikeplus64/aeson-flowtyped][aeson-flowtyped]], a Haskell library for generating FlowType or TypeScript type
declarations to match ~aeson~'s ~ToJSON~ / ~FromJSON~ instances.

[[https://gitlab.com/transportengineering/csvmaps][csvmaps]], a tool for manipulating map-like .csv files.

[[http://quasimal.com/projects/plissken.html][plissken]], a 3D Snake clone, where the Snake moves in 3 dimensions. Used
~OpenGLRaw~, ~hmatrix~, ~GLFW-b~ and ~lens~.

[[http://quasimal.com/projects/level_0.html][Level-0]], a clone of the [[https://en.wikipedia.org/wiki/Nokia_1100][Nokia 1100]]'s *Snake II* using the SDL bindings for
Haskell.

[[http://hackage.haskell.com/package/indices][indices]], a library providing statically bounded array indices, enable static
unrolling of critical loops performing array operations.

[[http://hackage.haskell.org/package/QuasiText][QuasiText]], a simple ~QuasiQuoter~ for interpolating Haskell values into ~Text~
strings.

[[https://github.com/ANU-Linked-Earth-Data][Linked Earth Data]], an explorative team project to deliver a highly interoperable
 DGGS/Linked data → SPARQL/REST endpoint, in order to inform future W3C and OGC
 standards [[https://www.w3.org/2015/spatial/charter][future W3C and OGC standards]]. Makes use of variable-resolution
 satellite imagery made available in the [[http://www.datacube.org.au/][Australian Geoscience Datacube]]. My
 involvement was limited -- I participated only in the first half of this
 project in order to pursue full-time work because I could no-longer afford uni
 at the time.

** Open source contributions

[[http://hackage.haskell.org/package/snaplet-recaptcha][snaplet-recaptcha]]
- Updated for new ReCAPTCHA API
- Heist support
- Hackage maintainership
 
[[http://hackage.haskell.org/package/hasql][hasql]]
- Support for PostgreSQL composite types

[[http://hackage.haskell.org/package/lens][lens]]
- Initial ~makeFields~ implementation.

[[http://redeclipse.net][Red Eclipse]] 
- 3D modelling and animation
- Community support
- Automated Linux builds

[[http://hackage.haskell.org/package/hmatrix][hmatrix]]
- FFI helpers

