---
title: Mike Ledger
author: Mike Ledger
date: 8 January, 2018
description: My resume
---
#+BEGIN_HTML
<div id="header">
<div id="details">
#+END_HTML

|----------+-------------------|
|          | *Mike Ledger*     |
| Email    | [[mailto:mike@quasimal.com][mike@quasimal.com]] |
| Website  | [[http://quasimal.com][quasimal.com]]      |
| Phone    | [[tel:+61403154462][+61 403 154 462]]   |
| Accounts | [[https://github.com/mikeplus64][GitHub]], [[http://hackage.haskell.org/user/MikeLedger][Hackage]]   |
|----------+-------------------|

#+BEGIN_HTML
<img id="gravatar" alt="Gravatar" src="https://secure.gravatar.com/avatar/c9f4d28a5240e2b99d83a5848f49c01f?s=200" title="Gravatar (Wallace and Gromit: A Grand Day Out)" />
<div style="clear: both"></div>
</div>
</div>

<div id="content">
#+END_HTML

I'm a programmer (and [[http:/gallery][occasional artist]]) living in Sydney, Australia. I'm 3
years into a [[http://programsandcourses.anu.edu.au/program/AACOM][BAC]]. Currently I'm developing [[https://respecify.com][Respecify]] at [[http://transportengineering.com.au][Transport Engineering]].

#+BEGIN_HTML 
<div id="skills">
#+END_HTML

|--------------+--------+-----------+---------------|
| Haskell      | SQL    | C         | Linux admin   |
| Python       | Java   | C#        | HTML/CSS      |
| JavaScript   | Git    | Mercurial | OpenGL / GLSL |
| Visual Basic | Design | RDF       | ... and more  |
|--------------+--------+-----------+---------------|

I have experience with parser generators and parsing natural language through my
work on [[https://respecify.com][Respecify]] -- I've designed and implemented a parser generator
specifically for it, which enables fast parsing of requirements, and extraction
of relationships.

I have a great deal of experience with developing web servers/backends, where my
experience is in using [[http://yesodweb.com][Yesod]], [[http://snapframework.com][Snap]] and [[http://flask.pocoo.org/][Flask]] (where I also gained experience
with the wonderful [[http://www.sqlalchemy.org/][SQLAlchemy]]). Through Respecify I have experience with
WebSocket-based single-page applications. I'm proficient with PostgreSQL
databases where I have experience benchmarking for efficient and minimal
queries.

I have some experience with writing (and Respecify'ing :-)) technical
requirements through work on Parramatta Light Rail.

#+BEGIN_HTML 
</div>
#+END_HTML

** Public work

[[https://respecify.com][Respecify]], a requirements authoring tool utilising constrained natural language.
I have developed this (so far) as a one-man team. Respecify was presented in
Lisbon for [[http://re2017.org][RE'17]]. [[http://ieeexplore.ieee.org/document/8049164/][Paper available online at IEEE Xplore]].

[[http://transportengineering.com.au][Transport Engineering website]], a simple-ish Hakyll-generated website that runs
in parallel with an older Wordpress-based website.

[[https://github.com/mikeplus64/teamsplat][teamsplat]], a simple team splitter to generate fair teams for 8-ish player games.
Live version available on [[https://teamsplat.herokuapp.com][Heroku]] (because it's free and Good Enough!).

[[https://gitlab.com/transportengineering/rnd/radixtree][radixtree]], a prefix-tree parsing library for Haskell. Used extensively by
Respecify.

[[https://github.com/TransportEngineering/nice-html][nice-html]], a XML/HTML templating library for Haskell. Has distinct template
compilation and rendering phases, which is its main advantage over e.g., Lucid
or Blaze.

[[https://github.com/mikeplus64/aeson-flowtyped][aeson-flowtyped]], a Haskell library for generating Flowtype type declarations to
match ~aeson~'s ~ToJSON~ / ~FromJSON~ instances.

[[http://quasimal.com/projects/plissken.html][plissken]], a 3D Snake clone, where the Snake moves in 3 dimensions. Used
~OpenGLRaw~, ~hmatrix~, ~GLFW-b~ and ~lens~.

[[http://quasimal.com/projects/level_0.html][Level-0]], a clone of the [[https://en.wikipedia.org/wiki/Nokia_1100][Nokia 1100]]'s *Snake II* using the SDL bindings for
Haskell.

[[http://hackage.haskell.com/package/indices][indices]], a library providing statically bounded array indices, extensively
making use of GHC features to have extremely little runtime overhead.

[[https://github.com/mikeplus64/static][static]], a new array library for statically bounded arrays, unrolling operations
at compile-time where possible.

[[http://hackage.haskell.org/package/QuasiText][QuasiText]], a simple ~QuasiQuoter~ for interpolating Haskell values into ~Text~
strings.

[[https://github.com/ANU-Linked-Earth-Data][Linked Earth Data]], an explorative team project to deliver a highly interoperable
 DGGS/Linked data → SPARQL/REST endpoint, in order to inform future W3C and OGC
 standards [[https://www.w3.org/2015/spatial/charter][future W3C and OGC standards]]. Makes use of variable-resolution
 satellite imagery made available in the [[http://www.datacube.org.au/][Australian Geoscience Datacube]]. My
 involvement was limited -- I left uni for full-time work because I could
 no-longer afford it.

** Open source contributions

[[http://hackage.haskell.org/package/snaplet-recaptcha][snaplet-recaptcha]]
- Updated for new ReCAPTCHA API
- Heist support
- Hackage maintainership
 
[[http://hackage.haskell.org/package/hasql][hasql]]
- Support for PostgreSQL composite types

[[http://hackage.haskell.org/package/lens][lens]]
- Initial ~makeFields~ implementation.

[[http://redeclipse.net][Red Eclipse]] 
- 3D modelling and animation
- Community support
- Automated Linux builds

[[http://hackage.haskell.org/package/hmatrix][hmatrix]]
- FFI helpers

